version: "3"

services:
  centrifugo:
    image: centrifugo/centrifugo:v6
    container_name: centrifugo
    command: centrifugo -c config.json
    ports:
      - "8000:8000"
    volumes:
      - ./centrifugo:/centrifugo
    environment:
      - CENTRIFUGO_ADMIN=true
      - CENTRIFUGO_TOKEN_HMAC_SECRET_KEY=your_256_bit_secret_key_that_is_long_enough_for_hmac_sha
